export const TIME_ZONES = [
    { value: 'Pacific/Midway', label: '(UTC-11:00) Midway Island, Samoa' },
    { value: 'Pacific/Honolulu', label: '(UTC-10:00) Hawaii' },
    { value: 'America/Anchorage', label: '(UTC-09:00) Alaska' },
    { value: 'America/Los_Angeles', label: '(UTC-08:00) Pacific Time (US & Canada)' },
    { value: 'America/Tijuana', label: '(UTC-08:00) Tijuana, Baja California' },
    { value: 'America/Denver', label: '(UTC-07:00) Mountain Time (US & Canada)' },
    { value: 'America/Chihuahua', label: '(UTC-07:00) Chihuahua, La Paz' },
    { value: 'America/Phoenix', label: '(UTC-07:00) Arizona' },
    { value: 'America/Chicago', label: '(UTC-06:00) Central Time (US & Canada)' },
    { value: 'America/Regina', label: '(UTC-06:00) Saskatchewan' },
    { value: 'America/Mexico_City', label: '(UTC-06:00) Guadalajara, Mexico City' },
    { value: 'America/New_York', label: '(UTC-05:00) Eastern Time (US & Canada)' },
    { value: 'America/Bogota', label: '(UTC-05:00) Bogota, Lima, Quito' },
    { value: 'America/Caracas', label: '(UTC-04:00) Caracas' },
    { value: 'America/Halifax', label: '(UTC-04:00) Atlantic Time (Canada)' },
    { value: 'America/Manaus', label: '(UTC-04:00) Manaus' },
    { value: 'America/Santiago', label: '(UTC-04:00) Santiago' },
    { value: 'America/St_Johns', label: '(UTC-03:30) Newfoundland' },
    { value: 'America/Sao_Paulo', label: '(UTC-03:00) Brasilia' },
    { value: 'America/Argentina/Buenos_Aires', label: '(UTC-03:00) Buenos Aires, Georgetown' },
    { value: 'America/Godthab', label: '(UTC-03:00) Greenland' },
    { value: 'Atlantic/South_Georgia', label: '(UTC-02:00) Mid-Atlantic' },
    { value: 'Atlantic/Azores', label: '(UTC-01:00) Azores' },
    { value: 'Atlantic/Cape_Verde', label: '(UTC-01:00) Cape Verde Is.' },
    { value: 'UTC', label: '(UTC+00:00) Coordinated Universal Time' },
    { value: 'Europe/London', label: '(UTC+00:00) London, Edinburgh, Dublin' },
    { value: 'Europe/Lisbon', label: '(UTC+00:00) Lisbon' },
    { value: 'Africa/Casablanca', label: '(UTC+00:00) Casablanca, Monrovia' },
    { value: 'Europe/Belgrade', label: '(UTC+01:00) Belgrade, Bratislava, Budapest' },
    { value: 'Europe/Paris', label: '(UTC+01:00) Paris, Madrid, Copenhagen' },
    { value: 'Europe/Rome', label: '(UTC+01:00) Rome' },
    { value: 'Europe/Berlin', label: '(UTC+01:00) Berlin, Bern, Stockholm, Vienna' },
    { value: 'Europe/Amsterdam', label: '(UTC+01:00) Amsterdam, Berlin, Rome' },
    { value: 'Africa/Lagos', label: '(UTC+01:00) West Central Africa' },
    { value: 'Europe/Bucharest', label: '(UTC+02:00) Bucharest' },
    { value: 'Africa/Cairo', label: '(UTC+02:00) Cairo' },
    { value: 'Europe/Helsinki', label: '(UTC+02:00) Helsinki, Kyiv, Riga' },
    { value: 'Europe/Istanbul', label: '(UTC+03:00) Istanbul' },
    { value: 'Asia/Jerusalem', label: '(UTC+02:00) Jerusalem' },
    { value: 'Africa/Johannesburg', label: '(UTC+02:00) Harare, Pretoria' },
    { value: 'Asia/Kuwait', label: '(UTC+03:00) Kuwait, Riyadh' },
    { value: 'Europe/Moscow', label: '(UTC+03:00) Moscow, St. Petersburg' },
    { value: 'Africa/Nairobi', label: '(UTC+03:00) Nairobi' },
    { value: 'Asia/Baghdad', label: '(UTC+03:00) Baghdad' },
    { value: 'Asia/Tehran', label: '(UTC+03:30) Tehran' },
    { value: 'Asia/Dubai', label: '(UTC+04:00) Abu Dhabi, Muscat' },
    { value: 'Asia/Baku', label: '(UTC+04:00) Baku' },
    { value: 'Asia/Kabul', label: '(UTC+04:30) Kabul' },
    { value: 'Asia/Yekaterinburg', label: '(UTC+05:00) Ekaterinburg' },
    { value: 'Asia/Karachi', label: '(UTC+05:00) Islamabad, Karachi' },
    { value: 'Asia/Kolkata', label: '(UTC+05:30) Chennai, Kolkata, Mumbai, New Delhi' },
    { value: 'Asia/Kathmandu', label: '(UTC+05:45) Kathmandu' },
    { value: 'Asia/Dhaka', label: '(UTC+06:00) Dhaka' },
    { value: 'Asia/Almaty', label: '(UTC+06:00) Almaty, Novosibirsk' },
    { value: 'Asia/Rangoon', label: '(UTC+06:30) Yangon (Rangoon)' },
    { value: 'Asia/Bangkok', label: '(UTC+07:00) Bangkok, Hanoi, Jakarta' },
    { value: 'Asia/Krasnoyarsk', label: '(UTC+07:00) Krasnoyarsk' },
    { value: 'Asia/Hong_Kong', label: '(UTC+08:00) Beijing, Chongqing, Hong Kong' },
    { value: 'Asia/Kuala_Lumpur', label: '(UTC+08:00) Kuala Lumpur, Singapore' },
    { value: 'Asia/Taipei', label: '(UTC+08:00) Taipei' },
    { value: 'Australia/Perth', label: '(UTC+08:00) Perth' },
    { value: 'Asia/Irkutsk', label: '(UTC+08:00) Irkutsk, Ulaan Bataar' },
    { value: 'Asia/Tokyo', label: '(UTC+09:00) Osaka, Sapporo, Tokyo' },
    { value: 'Asia/Seoul', label: '(UTC+09:00) Seoul' },
    { value: 'Asia/Yakutsk', label: '(UTC+09:00) Yakutsk' },
    { value: 'Australia/Adelaide', label: '(UTC+09:30) Adelaide' },
    { value: 'Australia/Darwin', label: '(UTC+09:30) Darwin' },
    { value: 'Australia/Brisbane', label: '(UTC+10:00) Brisbane' },
    { value: 'Australia/Sydney', label: '(UTC+10:00) Canberra, Melbourne, Sydney' },
    { value: 'Pacific/Guam', label: '(UTC+10:00) Guam, Port Moresby' },
    { value: 'Australia/Hobart', label: '(UTC+10:00) Hobart' },
    { value: 'Asia/Vladivostok', label: '(UTC+10:00) Vladivostok' },
    { value: 'Pacific/Noumea', label: '(UTC+11:00) Solomon Is., New Caledonia' },
    { value: 'Pacific/Auckland', label: '(UTC+12:00) Auckland, Wellington' },
    { value: 'Pacific/Fiji', label: '(UTC+12:00) Fiji, Kamchatka, Marshall Is.' },
    { value: 'Pacific/Tongatapu', label: '(UTC+13:00) Nuku\'alofa' }
];

export const getTimeZoneLabel = (timeZoneValue: string): string => {
    const zone = TIME_ZONES.find(z => z.value === timeZoneValue);
    return zone ? zone.label : timeZoneValue;
};
